version: '3.4'

services:
  database:
    container_name: database
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1435:1433"
    env_file:
      - database.env
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: WMS.WebApi/Dockerfile
    ports:
      - "6578:80"
    depends_on:
      - database
  
  frontend:
    container_name: frontend
    build:
      context: ./WMS.Frontend/
      dockerfile: Dockerfile
    ports:
      - "4014:4200"
    depends_on:
      - api