// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMS.Database;

#nullable disable

namespace WMS.Database.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20221203195443_UpdateAddress")]
    partial class UpdateAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ShelfId")
                        .IsUnique()
                        .HasFilter("[ShelfId] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MaxShelfs")
                        .HasColumnType("int");

                    b.Property<int>("MaxVerticalSections")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Rack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Index", "AreaId")
                        .IsUnique();

                    b.ToTable("Racks");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("VerticalSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerticalSectionId");

                    b.HasIndex("Index", "VerticalSectionId")
                        .IsUnique();

                    b.ToTable("Shelfs");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.VerticalSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("RackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.HasIndex("Index", "RackId")
                        .IsUnique();

                    b.ToTable("VerticalSections");
                });

            modelBuilder.Entity("WMS.Database.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WMS.Database.Entities.Dictionaries.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasurement");
                });

            modelBuilder.Entity("WMS.Database.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AuditorId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastUpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("int");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditorId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("PerformerId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WMS.Database.Entities.Tenants.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("WMS.Database.Entities.Tenants.LegalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UNN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UNN")
                        .IsUnique();

                    b.ToTable("LegalEntities");
                });

            modelBuilder.Entity("WMS.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WMS.Database.Entities.Ware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("LegalEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TechnicalParameterValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitOfMeasurementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("IndividualId");

                    b.HasIndex("LegalEntityId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("Wares");
                });

            modelBuilder.Entity("WMS.Database.Entities.WareTask", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("WareId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "WareId");

                    b.HasIndex("WareId");

                    b.ToTable("WareTasks");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Address", b =>
                {
                    b.HasOne("WMS.Database.Entities.Addresses.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Database.Entities.Addresses.Shelf", "Shelf")
                        .WithOne("Address")
                        .HasForeignKey("WMS.Database.Entities.Addresses.Address", "ShelfId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Area");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Rack", b =>
                {
                    b.HasOne("WMS.Database.Entities.Addresses.Area", "Area")
                        .WithMany("Racks")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Shelf", b =>
                {
                    b.HasOne("WMS.Database.Entities.Addresses.VerticalSection", "VerticalSection")
                        .WithMany("Shelfs")
                        .HasForeignKey("VerticalSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerticalSection");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.VerticalSection", b =>
                {
                    b.HasOne("WMS.Database.Entities.Addresses.Rack", "Rack")
                        .WithMany("VerticalSections")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("WMS.Database.Entities.Comment", b =>
                {
                    b.HasOne("WMS.Database.Entities.User", "Owner")
                        .WithMany("Comments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WMS.Database.Entities.Task", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WMS.Database.Entities.Task", b =>
                {
                    b.HasOne("WMS.Database.Entities.User", "Auditor")
                        .WithMany("AuditorTasks")
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WMS.Database.Entities.User", "Author")
                        .WithMany("AuthorTasks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Database.Entities.Task", "ParentTask")
                        .WithMany("ChildTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WMS.Database.Entities.User", "Performer")
                        .WithMany("PerformerTasks")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Auditor");

                    b.Navigation("Author");

                    b.Navigation("ParentTask");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("WMS.Database.Entities.Ware", b =>
                {
                    b.HasOne("WMS.Database.Entities.Addresses.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Database.Entities.Tenants.Individual", "Individual")
                        .WithMany("Wares")
                        .HasForeignKey("IndividualId");

                    b.HasOne("WMS.Database.Entities.Tenants.LegalEntity", "LegalEntity")
                        .WithMany("Wares")
                        .HasForeignKey("LegalEntityId");

                    b.HasOne("WMS.Database.Entities.Dictionaries.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Wares")
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Individual");

                    b.Navigation("LegalEntity");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("WMS.Database.Entities.WareTask", b =>
                {
                    b.HasOne("WMS.Database.Entities.Task", "Task")
                        .WithMany("Wares")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Database.Entities.Ware", "Ware")
                        .WithMany("Tasks")
                        .HasForeignKey("WareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Ware");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Area", b =>
                {
                    b.Navigation("Racks");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Rack", b =>
                {
                    b.Navigation("VerticalSections");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.Shelf", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("WMS.Database.Entities.Addresses.VerticalSection", b =>
                {
                    b.Navigation("Shelfs");
                });

            modelBuilder.Entity("WMS.Database.Entities.Dictionaries.UnitOfMeasurement", b =>
                {
                    b.Navigation("Wares");
                });

            modelBuilder.Entity("WMS.Database.Entities.Task", b =>
                {
                    b.Navigation("ChildTasks");

                    b.Navigation("Comments");

                    b.Navigation("Wares");
                });

            modelBuilder.Entity("WMS.Database.Entities.Tenants.Individual", b =>
                {
                    b.Navigation("Wares");
                });

            modelBuilder.Entity("WMS.Database.Entities.Tenants.LegalEntity", b =>
                {
                    b.Navigation("Wares");
                });

            modelBuilder.Entity("WMS.Database.Entities.User", b =>
                {
                    b.Navigation("AuditorTasks");

                    b.Navigation("AuthorTasks");

                    b.Navigation("Comments");

                    b.Navigation("PerformerTasks");
                });

            modelBuilder.Entity("WMS.Database.Entities.Ware", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
